---
title: "session 4 notes"
author: "Tim Riffe"
date: "2024-07-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Stationary population

```{r, message = FALSE}
library(tidyverse)
source("https://raw.githubusercontent.com/timriffe/KOSTAT_Workshop1/master/lifetable_functions_2024.R")

mx <- read_csv('https://github.com/timriffe/KOSTAT_Workshop1/raw/master/Data/mx1dt.csv.gz')
```

Note, lx is proportional to what the stationary population structure would be if the same number of births entered each year and mortality never changed over time.

```{r}
world <-
  mx |> 
  filter(country_code == 900,
         year == 2019) |> 
  select(-mxB) |> 
  rename(m = mxM, f = mxF) |> 
  pivot_longer(c(m,f),
               names_to = "sex",
               values_to = "mx") |> 
  arrange(sex, age)
```

Now we have a clean subset that can be used for later calculations
First, derive Lx
```{r}
SRB <- 1.05
(PF <- 1 / (1 + SRB))
stationary <-
  world |> 
  group_by(sex) |> 
  mutate(ax = if_else(age == 0, .1, .5),
         n = rep(1,n())) |> 
  group_modify(~calc_LT_tidy(data = .x)) |> 
  select(sex, age, Lx) |> 
  # Cx is structure, implying a shared total radix of 1
  mutate(Cx = Lx * if_else(sex == "f", PF, 1 - PF)) |> 
  ungroup() |> 
  mutate(Cx = 100 * Cx / sum(Cx))
```

Plot it!

```{r}
stationary |> 
  mutate(Cx = Cx * if_else(sex == "m", -1, 1)) |> 
  ggplot(aes(x = age, y = Cx, fill = sex)) +
  geom_col(width = 1, alpha = .6) +
  theme_minimal() +
  scale_y_continuous(breaks = seq(-.75, .75, by = .25),
                     labels = c(".75",".50",".25","",".25",".50",".75")) +
  geom_hline(yintercept = seq(-.75, .75, by = .25), 
             color = "white",
             linewidth = .5) +
  scale_x_continuous(breaks = seq(0,100,by=20)) +
  geom_vline(xintercept = seq(0,100,by=20), 
             color = "white", 
             linewidth = .5) +
  coord_flip() +
  scale_fill_manual(values = c(m = "#5c9c6c", f = "#965c9c"))
```

What about 5-year age groups?

```{r}
0:10 - 0:10 %% 5
```


```{r}
stationary |> 
  mutate(age = age - age %% 5) |> 
  group_by(sex, age) |> 
  summarize(Cx = sum(Cx), .groups = "drop") |> 
  mutate(Cx = Cx * if_else(sex == "m", -1, 1) / 5) |> 
  
  ggplot(aes(x = age, y = Cx, fill = sex)) +
  geom_col(width = 5, alpha = .6) +
  theme_minimal() +
  geom_hline(yintercept = seq(-.75, .75, by = .25), 
             color = "white",
             linewidth = .5) +
  scale_x_continuous(breaks = seq(0,100,by=20)) +
  geom_vline(xintercept = seq(0,100,by=20), 
             color = "white", 
             linewidth = .5) +
  coord_flip() +
  scale_fill_manual(values = c(m = "#5c9c6c", f = "#965c9c")) +
  guides(fill = "none")
```


















