---
title: "Session 5 notes"
author: "Tim Riffe"
date: "7/30/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary

1. Download the data
2. Harmonize the data
3. Join the data
4. Visualize it

## GBD

```{r}
library(here)
gbd_url <- "https://s3.healthdata.org/gbd-api-2017-public/835b25c27d7b31e221f6c51f7756875b_files/IHME-GBD_2017_DATA-835b25c2-1.zip"

local_file_gbd <- here("Data","GBD_prevalence.zip")

if (!file.exists(local_file_gbd)){
  download.file(gbd_url, destfile = local_file_gbd)
}
```

## HLD

```{r}
hld_url <- "https://www.lifetable.de/data/hld.zip"
local_file_hld <- here("Data","HLD.zip")

if (! file.exists(local_file_hld)){
  download.file(hld_url, destfile = local_file_hld)
}
```


# Read in the data

## GBD

```{r}
library(tidyverse)
library(readr)
GBD <- read_csv(local_file_gbd)
glimpse(GBD)
GBD$cause %>% unique()
```

## HLD

```{r}
HLD <- read_csv(local_file_hld)
```
# Harmonize the data to be able to merge

## GBD
```{r}
# install.packages("countrycode")
library(countrycode)
GBD$age %>% unique()
# substr("My name is Tim", start = 1, stop = 2)
GBD <-
  # incoming GBD, will only work on first run, because
  # we over-write
  GBD %>% 
         # recode age in 3 steps
  mutate(age = substr(age, start = 1, stop = 2),
         age = ifelse(age == "<1", "0", age),
         age = parse_number(age),
         # recode sex to some standard
         sex = case_when(sex == "Male" ~ "m",
                         sex == "Female" ~ "f",
                         sex == "Both" ~ "t"),
         # use the countrycode package to find ISO3 codes
         # because that's easier to match on.
         ISO3 = countrycode(location,
                            origin = "country.name",
                            destination = "iso3c")) 
```

## 

```{r}
GBD %>% 
  filter(location == "India") %>% 
  ggplot(aes(x = age, y = val, color = sex)) +
  geom_line() +
  geom_ribbon(aes(ymin = lower,
                  ymax = upper,
                  fill = sex),
              alpha = .2,
              color = NA)+
  facet_wrap(~cause)
```

## Filter down

```{r}
GBD <-
  GBD %>% 
  filter(cause != "All causes")
```


## HLD prep

```{r}
HLD <- 
  HLD %>% 
  # filter down to nationally representative lifetables
  filter(Ethnicity == "0",
         Residence == "0",
         Region == "0",
         # abridged ages are codes > 1
         TypeLT > 1,
         # recent years only
         Year1 >= 2012) %>% 
  
  # create a distance to 2017.5 indicator
  mutate(Year = (Year1 + Year2 + 1) / 2,
         Diff = 2017.5 - Year,
         Dist = abs(Diff)) %>% 
  
  # figure out which subsets minimize this
  group_by(Country, Sex) %>% 
  mutate(keep = Dist == min(Dist)) %>% 
  
  # create a second stricter condition, just in case
  # we have equal distances on the left and right
  group_by(Country, Sex, keep) %>% 
  mutate(keep2 = keep & Year == max(Year)) %>% 
  ungroup() %>% 
  filter(keep2) %>% 
  # group down the open age to the lowest
  # common denominator. No effect on LE
  mutate(Age = ifelse(Age >= 80, 80, Age)) %>% 
  group_by(Country, Sex, Age) %>% 
  summarize(nLx = sum(`L(x)`), 
            .groups = "drop") %>% 
  # harmonize radix to 1
  mutate(radix = ifelse(Country %in% c("Malta","Turkmenistan"), 10000, 100000),
         nLx = nLx / radix,
         Sex = ifelse(Sex == 1, "m","f")) %>% 
  
  # take care of renaming when we select final columns
  select(ISO3 = Country,
         sex = Sex,
         age = Age,
         nLx)
  
```


# Ready to join























